# Generated by Django 6.0.5 on 2026-05-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('narration', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InternalLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('bank', 'Bank'), ('internal', 'Internal')], max_length=10)),
                ('reconciliation_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched')], default='unmatched', max_length=20)),
                ('bank_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers', to='api.bankstatement')),
                ('internal_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers', to='api.internalledger')),
            ],
        ),
    ]
